defmodule ExAutoresearch.Repo.Migrations.AddTrustLayer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sources, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :scraper_source, :text
      add :relevance_score, :float
      add :content_hash, :text
      add :fetched_at, :utc_datetime_usec
      add :title, :text
      add :domain, :text
      add :url, :text, null: false

      add :investigation_id,
          references(:investigations,
            column: :id,
            name: "sources_investigation_id_fkey",
            type: :uuid
          )

      add :report_id,
          references(:reports, column: :id, name: "sources_report_id_fkey", type: :uuid),
          null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:sources, [:report_id, :url], name: "sources_unique_report_url_index")

    create table(:claims, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :order_index, :bigint
      add :claim_hash, :text
      add :origin_subquery, :text
      add :confidence, :float
      add :grounding, :text
      add :text, :text, null: false

      add :source_id,
          references(:sources, column: :id, name: "claims_source_id_fkey", type: :uuid)

      add :report_id,
          references(:reports, column: :id, name: "claims_report_id_fkey", type: :uuid),
          null: false

      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claims` table without the `claims_report_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `claims` table without the `claims_source_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:claims)

    drop_if_exists unique_index(:sources, [:report_id, :url],
                     name: "sources_unique_report_url_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `sources` table without the `sources_report_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `sources` table without the `sources_investigation_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:sources)
  end
end
