defmodule ExAutoresearch.Repo.Migrations.AddGpuToTrials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:trials) do
      add :gpu, :text
    end
  end

  def down do
    alter table(:trials) do
      remove :gpu
    end
  end
end