defmodule ExAutoresearch.Repo.Migrations.AddInvestigationProvenance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:investigations) do
      add :fetched_at, :utc_datetime_usec
      add :content_hash, :text
      add :scraper_source, :text
      add :fallback_used, :boolean
    end
  end

  def down do
    alter table(:investigations) do
      remove :fallback_used
      remove :scraper_source
      remove :content_hash
      remove :fetched_at
    end
  end
end
