defmodule ExAutoresearch.Repo.Migrations.AddClaimContradictingSourceIds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:claims) do
      add :contradicting_source_ids, {:array, :uuid}
    end
  end

  def down do
    alter table(:claims) do
      remove :contradicting_source_ids
    end
  end
end
