defmodule ExAutoresearch.Repo.Migrations.AddReportLlmUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reports) do
      add :total_input_tokens, :bigint
      add :total_output_tokens, :bigint
      add :llm_calls_count, :bigint
    end
  end

  def down do
    alter table(:reports) do
      remove :llm_calls_count
      remove :total_output_tokens
      remove :total_input_tokens
    end
  end
end
