defmodule ExAutoresearch.Repo.Migrations.CampaignTrialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:trials, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :error, :text
      add :kept, :boolean
      add :num_steps, :bigint
      add :training_seconds, :float
      add :final_loss, :float
      add :config, :map
      add :model, :text
      add :parent_id, :uuid
      add :reasoning, :text
      add :description, :text
      add :code, :text
      add :status, :text
      add :version_id, :text, null: false

      add :campaign_id,
          references(:campaigns, column: :id, name: "trials_campaign_id_fkey", type: :uuid),
          null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create table(:campaigns, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :best_trial_id, :uuid
      add :base_config, :map
      add :time_budget, :bigint
      add :model, :text
      add :status, :text
      add :tag, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:campaigns, [:tag], name: "campaigns_unique_tag_index")
  end

  def down do
    drop_if_exists unique_index(:campaigns, [:tag], name: "campaigns_unique_tag_index")

    drop table(:campaigns)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `trials` table without the `trials_campaign_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:trials)
  end
end
