defmodule ExAutoresearch.Repo.Migrations.AddDelta do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deltas, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :generated_at, :utc_datetime_usec
      add :read_at, :utc_datetime_usec
      add :contradicted_count, :bigint
      add :removed_count, :bigint
      add :changed_count, :bigint
      add :added_count, :bigint
      add :markdown_digest, :text
      add :to_report_id, :uuid, null: false
      add :from_report_id, :uuid
      add :organization_id, :uuid, null: false
      add :brief_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:deltas)
  end
end
