defmodule ExAutoresearch.Repo.Migrations.AddBrief do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:briefs, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :next_run_at, :utc_datetime_usec
      add :last_run_at, :utc_datetime_usec
      add :notify_channels, {:array, :text}, default: []
      add :block_domains, {:array, :text}, default: []
      add :allow_domains, {:array, :text}, default: []
      add :max_sources, :bigint
      add :max_depth, :bigint
      add :model, :text

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "briefs_organization_id_fkey",
            type: :uuid
          ),
          null: false

      add :enabled, :boolean
      add :cadence, :text
      add :category, :text
      add :question, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:reports) do
      add :brief_id,
          references(:briefs,
            column: :id,
            with: [organization_id: :organization_id],
            match: :full,
            name: "reports_brief_id_fkey",
            type: :uuid
          )

      add :run_version, :bigint
    end
  end

  def down do
    alter table(:reports) do
      remove :run_version
      remove :brief_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `briefs` table without the `briefs_organization_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:briefs)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `reports` table without the `reports_brief_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
