defmodule ExAutoresearch.Repo.Migrations.InitialDeepResearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :role, :text
      add :password_hash, :text, null: false
      add :name, :text
      add :password, :text
      add :email, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users, [:email], name: "users_unique_user_email_index")

    create table(:templates, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tags, {:array, :text}, default: []
      add :model, :text
      add :max_sources, :bigint
      add :max_depth, :bigint
      add :enabled, :boolean
      add :schedule_cron, :text
      add :category, :text
      add :query_template, :text, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "templates_organization_id_fkey",
            type: :uuid
          ), null: false

      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:reports, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :summary, :text
      add :markdown_body, :text
      add :final_score, :float
      add :total_investigations, :bigint
      add :total_sources, :bigint
      add :progress_pct, :float
      add :current_step, :text
      add :max_sources, :bigint
      add :max_depth, :bigint
      add :tags, {:array, :text}, default: []
      add :category, :text

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "reports_organization_id_fkey",
            type: :uuid
          )

      add :model_reasoning, :text
      add :model, :text
      add :status, :text
      add :query, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:organizations, primary_key: false) do
      add :owner_id,
          references(:users, column: :id, name: "organizations_owner_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :plan, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:reports, [:organization_id, :title], name: "reports_unique_title_index")

    create table(:memberships, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :role, :text

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "memberships_organization_id_fkey",
            type: :uuid
          ), null: false

      add :user_id,
          references(:users, column: :id, name: "memberships_user_id_fkey", type: :uuid),
          null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create table(:investigations, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :error, :text
      add :url, :text
      add :content_length, :bigint
      add :sources_count, :bigint
      add :quality_score, :float
      add :findings, :text
      add :status, :text
      add :reasoning, :text
      add :tool, :text, null: false
      add :query, :text
      add :depth, :bigint

      add :report_id,
          references(:reports, column: :id, name: "investigations_report_id_fkey", type: :uuid),
          null: false

      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `investigations` table without the `investigations_report_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:investigations)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `memberships` table without the `memberships_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `memberships` table without the `memberships_organization_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:memberships)

    drop_if_exists unique_index(:reports, [:organization_id, :title],
                     name: "reports_unique_title_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `organizations` table without the `organizations_owner_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:organizations)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `reports` table without the `reports_organization_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:reports)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `templates` table without the `templates_organization_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:templates)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_user_email_index")

    drop table(:users)
  end
end