defmodule ExAutoresearch.Repo.Migrations.AddAuditEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_events, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, default: %{}
      add :summary, :text
      add :target_id, :text
      add :target_type, :text
      add :event_type, :text, null: false
      add :user_id, :uuid
      add :organization_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:audit_events)
  end
end
