defmodule ExAutoresearch.Repo.Migrations.AddLossHistoryAndUpdateTimeBudget do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:trials) do
      add :loss_history, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:trials) do
      remove :loss_history
    end
  end
end