defmodule ExAutoresearch.Repo.Migrations.AddStepBudget do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaigns) do
      add :step_budget, :bigint
    end
  end

  def down do
    alter table(:campaigns) do
      remove :step_budget
    end
  end
end