use std::fs;
use std::path::Path;

use chrono::Local;

use crate::error::Result;
use crate::html::{html_escape, trend_svg};
use crate::model::{Experiment, Status};
use crate::store::load_all_runs;

pub fn cmd_report(data_dir: &Path, output: &Path, title: Option<&str>) -> Result<()> {
    let runs = load_all_runs(data_dir)?;
    if runs.is_empty() {
        eprintln!("no experiments found.");
        return Ok(());
    }

    let title = title.unwrap_or("research experiment report");
    let all: Vec<_> = runs.iter().flat_map(|r| r.experiments.clone()).collect();
    let kept: Vec<_> = all.iter().filter(|e| e.status.is_kept()).collect();
    let crashed = all.iter().filter(|e| e.status == Status::Crash).count();

    let bpbs: Vec<f64> = kept
        .iter()
        .map(|e| e.val_bpb)
        .filter(|v| *v > 0.0)
        .collect();
    let best = bpbs.iter().copied().fold(f64::INFINITY, f64::min);
    let worst = bpbs.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let improvement = if worst.is_finite() && best.is_finite() {
        worst - best
    } else {
        0.0
    };

    let metric_points: Vec<(usize, f64)> = kept
        .iter()
        .enumerate()
        .map(|(i, e)| (i, e.val_bpb))
        .collect();
    let svg = if metric_points.is_empty() {
        "<p style='color:#6b7280'>no data</p>".to_string()
    } else {
        trend_svg(&metric_points, 1040, 280)
    };

    let rows = kept
        .iter()
        .enumerate()
        .map(|(i, e)| {
            format!(
                "<tr><td>{}</td><td>{:.6}</td><td>{:.1}</td><td><code>{}</code></td><td>{}</td></tr>",
                i + 1,
                e.val_bpb,
                e.memory_gb,
                html_escape(&e.commit),
                html_escape(&e.description)
            )
        })
        .collect::<String>();

    let run_rows = runs
        .iter()
        .map(|r| {
            let b = r.best();
            format!(
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
                html_escape(&r.run_tag),
                b.map(|e| format!("{:.6}", e.val_bpb))
                    .unwrap_or_else(|| "—".into()),
                r.kept().count(),
                r.experiments
                    .iter()
                    .filter(|e| e.status == Status::Crash)
                    .count(),
            )
        })
        .collect::<String>();

    let body = format!(
        r#"<h1>{title}</h1>
<div class="sub">generated {generated} · {total} experiments across {n_runs} run(s)</div>

<div class="stats">
  <div class="stat"><div class="stat-val">{total}</div><div class="stat-label">total</div></div>
  <div class="stat"><div class="stat-val">{kept_n}</div><div class="stat-label">kept</div></div>
  <div class="stat"><div class="stat-val">{crashed}</div><div class="stat-label">crashed</div></div>
  <div class="stat"><div class="stat-val">{best_s}</div><div class="stat-label">best val_bpb</div></div>
  <div class="stat"><div class="stat-val">{imp_s}</div><div class="stat-label">improvement</div></div>
</div>

<h2>val_bpb trend</h2>
<div class="chart">{svg}</div>

<h2>kept experiments</h2>
<table><thead><tr><th>#</th><th>val_bpb</th><th>mem_gb</th><th>commit</th><th>description</th></tr></thead>
<tbody>{rows}</tbody></table>

<h2>runs</h2>
<table><thead><tr><th>run</th><th>best_val_bpb</th><th>kept</th><th>crashed</th></tr></thead>
<tbody>{run_rows}</tbody></table>"#,
        title = html_escape(title),
        generated = Local::now().format("%Y-%m-%d %H:%M"),
        total = all.len(),
        n_runs = runs.len(),
        kept_n = kept.len(),
        crashed = crashed,
        best_s = if best.is_finite() {
            format!("{best:.6}")
        } else {
            "—".into()
        },
        imp_s = if improvement > 0.0 {
            format!("{improvement:.6}")
        } else {
            "—".into()
        },
        svg = svg,
        rows = rows,
        run_rows = run_rows,
    );

    let page_title = format!("resman — {}", html_escape(title));
    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{}</title>
<style>{}</style>
</head>
<body>
{}
<footer>generated by resman · local-first experiment tracker</footer>
</body></html>"#,
        page_title,
        crate::html::CSS_DARK,
        body,
    );

    fs::write(output, html)?;
    println!("html report written to: {}", output.display());
    Ok(())
}

// Keep a thin local wrapper so existing call-sites in tests still compile.
fn _html_escape_local(s: &str) -> String {
    html_escape(s)
}

// Unused import suppression — the test uses Experiment via make_kept helper.
#[allow(dead_code)]
fn _use_experiment(_e: &Experiment) {}
